### ISSUE TITLE
Scoring SystemScore keeping

### ISSUE THREAD

**Issue by lcorndogl** [lcorndogl/Hackathon1-Wheel-of-Fortune#10]
**User Story**:
I want to see a score when a game finishes and compare to my previous attempts

**Acceptance Criteria:**
- [ ] Score increments with a correct guess
- [ ] Score decreases with an incorrect guess

**Tasks:**
- [ ] Check the current score and increment it on a correct guess
- [ ] Check the current score and decrement on incorrect guess
- [ ] Store the score at the end of the game and compare to highest score
