### ISSUE TITLE
Cheating

### ISSUE THREAD

**Issue by lcorndogl** [lcorndogl/Hackathon1-Wheel-of-Fortune#11]
**User Story**:
As a user I want to be able to get help if I am struggling to make a guess

**Acceptance Criteria:**
- [ ] User is able to request a letter to be filled in

**Tasks:**
- [ ] Check score to see if the user has enough points to cheat
- [ ] If the user has enough points, reveal a single letter
- [ ] If the user doesn't have enough points, display an error
