### ISSUE TITLE
Start/Retry Option

### ISSUE THREAD

**Issue by lcorndogl** [lcorndogl/Hackathon1-Wheel-of-Fortune#7]
**User Story**:
As a suer, I want to be able to start the game by clicking a start button, at the end of each game I want to be able to retry the game to beat my previous score(s)

**Acceptance Criteria:**

- [ ] On initial page load there needs to be a start game button
- [ ] On clicking start game, the button needs to change to a retry button

**Tasks:**
- [ ] Create a user action that triggers the start of the test
- [ ] Create a user action that triggers on clicking the retry button
