### ISSUE TITLE
User Guesses

### ISSUE THREAD

**Issue by lcorndogl** [lcorndogl/Hackathon1-Wheel-of-Fortune#9]
**User Story**:
As a user, I want to play a phrase guessing game, so that I can challenge my knowledge and have fun while trying to guess phrases.

**Acceptance Criteria:**
- [ ] The game should display a hidden phrase where each letter is represented by an underscore.
- [ ] Users should be able to guess a letter by typing it in.
- [ ] Correct guesses should replace the corresponding underscores with the guessed letter.
- [ ] Incorrect guesses should be tracked and displayed.

**Tasks:**
- [ ] Create a listener to listen for the user entries
- [ ] Check the input vs the answer
- [ ] Show the letter location if correct, or the whole answer if more than one character is guessed and correct
- [ ] Update the letters used
